version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    expose: 
    - 6379
  api:
    container_name: api
    build: .
    restart: unless-stopped
    ports:
      - 5000:5000
    links: 
      - redis
    environment:
      DB_CONNECT: 'mongodb+srv://Animakuro:fEzm9UPurpQdBG7e@cluster-animakuro.rhlenhv.mongodb.net/VE?retryWrites=true&w=majority'
      PORT: 5000
      JWT_ACCESS_SECRET: 'jwt_access_secret_key' 
      JWT_REFRESH_SECRET: 'jwt_refresh_secret_key' 
      JWT_EXP: '30m' 
      JWT_EXP_REFRESH: '30d'  
      SMTP_USER: "xayrullohabduvohidov713@gmail.com" 
      SMTP_PASSWORD: "hxqmhcteiaiigaih"
      RS_EXP: '300000'
      AWS_BUCKET_NAME: "visit--everywhere"
      AWS_BUCKET_REGION: "us-east-1"
      AWS_ACCESS_KEY: "AKIAZCZYNISOKRGON4RG"
      AWS_SECRET_KEY: "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"
volumes:
  mongo_db: {}
